sudo: false
language: ruby
bundler_args: "--without development production"
rvm:
  - 2.2.2
env:
  - SLOW_SPECS=true SKILLSHARE_SECRET_TOKEN=22d4eeff3dd0cdb77751cfd9b98dd442e7fd5ea9fad41c0331a89670df18589ffa96699300f9412fb2c456161903a6edc5b567c420ff6a573782e42a28375ac8
before_install:
  - gem install bundler -v '= 1.7.0'
before_script:
  rake db:create
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: <%= ENV["TRAVIS_API_KEY"] %>
