development:
  adapter: postgresql
  encoding: unicode
  database: skillshare_development
  pool: 5
  timeout: 5000
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: skillshare_test
  pool: 5
  timeout: 5000
  password:

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
